name: Ingest

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout workflow repository
        uses: actions/checkout@v2
      - name: Say Hello
        uses: "asengupta/test-composite-action/.github/workflows/actions/run-ast-generation@main"
